### ISSUE TITLE
delete() -> remove() в новой версии

### ISSUE THREAD

**Issue by Pushkinson** [Sakhnovkrg/Vue3-Yandex-SmartCaptcha#3]
Хочется узнать, когда новые изменения с remove() методом заедут в актуальную версию Vue3-Yandex-SmartCaptcha? Сейчас по команде ```npm install vue3-yandex-smartcaptcha``` устанавливается версия ```0.0.3```, а в ней используется прошлый код с delete() методом

**Comment by Sakhnovkrg** [comment]
Опубликовал
